### ISSUE TITLE
Add Primary Navigation

### ISSUE THREAD

**Issue by derick-montague** [gtmills/phosphor-webui-vue#13]
## Task
- [ ] Create layout of side nav and main content
- [ ] Determine Bootstrap components to use for left nav
- [ ] Update look and feel to match [existing BMC navigation](https://projects.invisionapp.com/share/DPT0CJ52AVC#/screens/394775350)
