### ISSUE TITLE
Add Login functionality

### ISSUE THREAD

**Issue by derick-montague** [gtmills/phosphor-webui-vue#14]
## Tasks
- [ ] Create the structural and presentational layers
- [ ] Determine how to use VueX for managing login state with BMC backend
- [ ] Add user service with login and logout functionality
